---
deployment:
  tasks:
    - /bin/rm -rf vendor
    - /bin/rm -rf node_modules
    - /home/br1hiswk5mtf/.bin/composer install
    - /bin/npm install
    - /bin/npm run build
    - export DEPLOYPATH=/home/br1hiswk5mtf/websites/nevadaspca.org
    - /bin/cp vendor -TR $DEPLOYPATH
    - /bin/cp node_modules -TR $DEPLOYPATH
    - /bin/cp config -TR $DEPLOYPATH/config
    - /bin/cp templates -TR $DEPLOYPATH
    - /bin/cp web -R $DEPLOYPATH
