field: 33cc23e5-4779-4efd-b2c7-8ff6a0893b3c # Article Content
fieldLayouts:
  abd32de9-4ef6-4659-9573-9a1e0f39f4a8:
    tabs:
      -
        elements:
          -
            fieldUid: 63443e71-ad70-4040-8a83-79016f2bdc27 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c82d3ecb-0686-421b-8e68-b8d91588206c # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f8bbc14b-300a-4dc7-91a2-e399117e2a56 # Atl Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  63443e71-ad70-4040-8a83-79016f2bdc27: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:cb909f1c-de9f-40e8-aef1-87699e1a5b6d' # Events
      defaultUploadLocationSubpath: images
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:d3280cf9-f4d9-4ff5-b08a-c6487b9680b4' # Images
      singleUploadLocationSubpath: img
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c82d3ecb-0686-421b-8e68-b8d91588206c: # Caption
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f8bbc14b-300a-4dc7-91a2-e399117e2a56: # Atl Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: atlText
    instructions: ''
    name: 'Atl Text'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: image
name: Image
sortOrder: 4
