fieldLayouts:
  9512241a-1860-4841-b7c4-487131266b11:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 039337f3-85db-4789-a73f-5dd98d787147 # Start Date / Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 3fa54afb-1a9f-40d9-b278-db8230ad126c # End Date / Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 9de60738-c953-48d7-ba61-e75afc5de5cb # Event Hero Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d9c28be-7c10-44dd-9ef6-2b5cab5a2221 # Event Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: events
hasTitleField: true
name: Events
section: 0b6d1b51-aa84-4cdc-a6e3-5bc7c593d0bd # Events
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
