fieldLayouts:
  103b3981-272a-4768-8eaa-94b8ed13852b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 6eb572a0-bb4d-4301-9c9a-9ae3b957e9eb # Article Summary
            instructions: ''
            label: Summary
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 707df1a0-6dbf-4974-a793-568e2003c826 # News Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 33cc23e5-4779-4efd-b2c7-8ff6a0893b3c # Article Content
            instructions: ''
            label: Content
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: news
hasTitleField: true
name: News
section: ef375224-61c9-4af9-9210-7a0503c3819c # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
