columnSuffix: null
contentColumnType: string(360)
fieldGroup: 5cb2b1e0-521d-4292-b1d0-e5aac1a6bf49 # Articles
handle: articleSummary
instructions: ''
name: 'Article Summary'
searchable: false
settings:
  byteLimit: null
  charLimit: 90
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
