columnSuffix: null
contentColumnType: string
fieldGroup: 5cb2b1e0-521d-4292-b1d0-e5aac1a6bf49 # Articles
handle: articleContent
instructions: ''
name: 'Article Content'
searchable: true
settings:
  contentTable: '{{%matrixcontent_articlecontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
