contentColumnType: datetime
fieldGroup: 7b386fd3-3446-443b-a78e-7ccbab721caf # Common
handle: endDateTime
instructions: ''
name: 'End Date / Time'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
