contentColumnType: text
fieldGroup: 8ce347be-2a45-4acd-b0b2-42339ed25250 # People
handle: firstName
instructions: ''
name: 'First Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
