contentColumnType: string
fieldGroup: 7b386fd3-3446-443b-a78e-7ccbab721caf # Common
handle: instagram
instructions: ''
name: Instagram
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 168c7456-d85d-4ab6-9233-cae08ea3a244 # Profile
        -
          __assoc__:
            -
              - width
              - ''
      -
        - e277e407-ceef-4c11-818f-f25f116b415e # Profile Url
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_instagram}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
