columnSuffix: null
contentColumnType: string
fieldGroup: 8ce347be-2a45-4acd-b0b2-42339ed25250 # People
handle: portrait
instructions: ''
name: Portrait
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:d3280cf9-f4d9-4ff5-b08a-c6487b9680b4' # Images
  defaultUploadLocationSubpath: img/
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add an image'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:cb909f1c-de9f-40e8-aef1-87699e1a5b6d' # Events
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:d3280cf9-f4d9-4ff5-b08a-c6487b9680b4' # Images
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
