contentColumnType: text
fieldGroup: 7b386fd3-3446-443b-a78e-7ccbab721caf # Common
handle: seoTitle
instructions: ''
name: Title
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
