field: e0e8b34a-3359-45d0-bc0f-3a841fd3dcff # Instagram
fieldLayouts:
  f4341ffa-9201-4747-ae22-c5d665e3f20a:
    tabs:
      -
        elements:
          -
            fieldUid: 168c7456-d85d-4ab6-9233-cae08ea3a244 # Profile
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e277e407-ceef-4c11-818f-f25f116b415e # Profile Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  168c7456-d85d-4ab6-9233-cae08ea3a244: # Profile
    contentColumnType: text
    fieldGroup: null
    handle: profile
    instructions: 'Your profile handle excluding the @ symbol'
    name: Profile
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e277e407-ceef-4c11-818f-f25f116b415e: # Profile Url
    contentColumnType: text
    fieldGroup: null
    handle: profileUrl
    instructions: 'Link to your profile page'
    name: 'Profile Url'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
