fieldLayouts:
  778cd2a4-affe-4c12-8012-fe782e208df1:
    tabs:
      -
        elements:
          -
            fieldUid: e1a16a3f-f4c8-4e6c-8016-dbcf9e95a6c3 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 135a7516-40d0-45c3-8365-22da1b52c36a # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Default
        sortOrder: 1
handle: seo
name: Seo
