enableVersioning: false
handle: contactForm
name: 'Contact Form'
propagationMethod: all
siteSettings:
  051a9101-1abd-4824-aa44-5e9ff5172a13: # Nevada SPCA
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
