enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  051a9101-1abd-4824-aa44-5e9ff5172a13: # Nevada SPCA
    enabledByDefault: true
    hasUrls: true
    template: home/index
    uriFormat: __home__
type: single
