defaultPlacement: end
enableVersioning: true
handle: shop
name: Shop
propagationMethod: all
siteSettings:
  051a9101-1abd-4824-aa44-5e9ff5172a13: # Nevada SPCA
    enabledByDefault: true
    hasUrls: true
    template: shop/_entry
    uriFormat: shop
type: single
