defaultPlacement: end
enableVersioning: true
handle: team
name: Team
propagationMethod: all
siteSettings:
  051a9101-1abd-4824-aa44-5e9ff5172a13: # Nevada SPCA
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 3df6639f-2b65-4560-be6e-5bbbf26f9dc4
type: structure
